"""Initial migration

Revision ID: c9aac6bf6f7d
Revises: 
Create Date: 2026-07-12 23:04:54.156653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9aac6bf6f7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime_heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_heads_code'), 'crime_heads', ['code'], unique=True)
    op.create_index(op.f('ix_crime_heads_id'), 'crime_heads', ['id'], unique=False)
    op.create_index(op.f('ix_crime_heads_name'), 'crime_heads', ['name'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_badge_number'), 'employees', ['badge_number'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_rank'), 'employees', ['rank'], unique=False)
    op.create_index(op.f('ix_employees_unit_name'), 'employees', ['unit_name'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_table('crime_sub_heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crime_head_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['crime_head_id'], ['crime_heads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_sub_heads_code'), 'crime_sub_heads', ['code'], unique=False)
    op.create_index(op.f('ix_crime_sub_heads_id'), 'crime_sub_heads', ['id'], unique=False)
    op.create_index(op.f('ix_crime_sub_heads_name'), 'crime_sub_heads', ['name'], unique=False)
    op.create_table('case_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fir_number', sa.String(length=100), nullable=False),
    sa.Column('incident_date', sa.DateTime(), nullable=False),
    sa.Column('registered_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('brief_facts', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.Column('crime_head_id', sa.Integer(), nullable=False),
    sa.Column('crime_subhead_id', sa.Integer(), nullable=False),
    sa.Column('investigating_officer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crime_head_id'], ['crime_heads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['crime_subhead_id'], ['crime_sub_heads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investigating_officer_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_master_district'), 'case_master', ['district'], unique=False)
    op.create_index(op.f('ix_case_master_fir_number'), 'case_master', ['fir_number'], unique=True)
    op.create_index(op.f('ix_case_master_id'), 'case_master', ['id'], unique=False)
    op.create_index(op.f('ix_case_master_incident_date'), 'case_master', ['incident_date'], unique=False)
    op.create_index(op.f('ix_case_master_registered_date'), 'case_master', ['registered_date'], unique=False)
    op.create_index(op.f('ix_case_master_status'), 'case_master', ['status'], unique=False)
    op.create_index(op.f('ix_case_master_unit_name'), 'case_master', ['unit_name'], unique=False)
    op.create_table('accused',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accused_id'), 'accused', ['id'], unique=False)
    op.create_index(op.f('ix_accused_name'), 'accused', ['name'], unique=False)
    op.create_table('victims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('injury_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_victims_id'), 'victims', ['id'], unique=False)
    op.create_index(op.f('ix_victims_name'), 'victims', ['name'], unique=False)
    op.create_table('arrest_surrenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('accused_id', sa.Integer(), nullable=False),
    sa.Column('arrest_date', sa.DateTime(), nullable=False),
    sa.Column('arrest_type', sa.String(length=50), nullable=False),
    sa.Column('arrest_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('court_name', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['accused_id'], ['accused.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['arrest_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['case_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arrest_surrenders_arrest_date'), 'arrest_surrenders', ['arrest_date'], unique=False)
    op.create_index(op.f('ix_arrest_surrenders_id'), 'arrest_surrenders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arrest_surrenders_id'), table_name='arrest_surrenders')
    op.drop_index(op.f('ix_arrest_surrenders_arrest_date'), table_name='arrest_surrenders')
    op.drop_table('arrest_surrenders')
    op.drop_index(op.f('ix_victims_name'), table_name='victims')
    op.drop_index(op.f('ix_victims_id'), table_name='victims')
    op.drop_table('victims')
    op.drop_index(op.f('ix_accused_name'), table_name='accused')
    op.drop_index(op.f('ix_accused_id'), table_name='accused')
    op.drop_table('accused')
    op.drop_index(op.f('ix_case_master_unit_name'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_status'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_registered_date'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_incident_date'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_id'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_fir_number'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_district'), table_name='case_master')
    op.drop_table('case_master')
    op.drop_index(op.f('ix_crime_sub_heads_name'), table_name='crime_sub_heads')
    op.drop_index(op.f('ix_crime_sub_heads_id'), table_name='crime_sub_heads')
    op.drop_index(op.f('ix_crime_sub_heads_code'), table_name='crime_sub_heads')
    op.drop_table('crime_sub_heads')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_unit_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_rank'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_badge_number'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_crime_heads_name'), table_name='crime_heads')
    op.drop_index(op.f('ix_crime_heads_id'), table_name='crime_heads')
    op.drop_index(op.f('ix_crime_heads_code'), table_name='crime_heads')
    op.drop_table('crime_heads')
    # ### end Alembic commands ###
